name: Deploy Nodejs Application

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}       
      - name: Build docker image
        run: docker build -t ghoang0004/fit5120-ausee .  
      - name: Publish image to docker hub
        run: docker push ghoang0004/fit5120-ausee:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull ghoang0004/fit5120-ausee:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container 
      - name: Run docker container
        run: docker run -d -p 80:80 --name nodejs-app-container ghoang0004/fit5120-ausee